source 'https://rubygems.org'

gem 'thin'
gem 'bson_ext'
gem 'mongo'
gem 'em-mongo'
gem 'async_sinatra'
gem 'chronic'
gem 'em-twitter'
gem 'faraday', '= 0.7.6'
gem 'multi_json', '~> 1.0.3'
gem 'instagram'
gem 'em-synchrony', '>= 1.0.0'
gem 'em-http-request'
gem 'eventmachine'
gem 'foreman', '>= 0.48.0.pre1'
